--------------------------------------------------------
-- === SCRIPT 01_CINE_00_users.sql ===
-- Ce fichier sql contient les commandes pour la création des utilisateurs de la base de données
--------------------------------------------------------

DROP USER CINE CASCADE;
DROP USER TP2235671 CASCADE;
DROP USER TP22363643 CASCADE;

CREATE USER CINE IDENTIFIED BY garneau;
CREATE USER TP2235671 IDENTIFIED BY garneau;
CREATE USER TP22363643 IDENTIFIED BY garneau;

GRANT CREATE SESSION TO CINE;
GRANT CREATE TABLE TO CINE;
GRANT CREATE VIEW TO CINE;
GRANT CREATE SEQUENCE TO CINE;
GRANT CREATE PROCEDURE TO CINE;

GRANT CREATE SESSION TO TP2235671;
GRANT CREATE SESSION TO TP22363643;

ALTER USER CINE QUOTA UNLIMITED ON USERS;