--------------------------------------------------------
-- === SCRIPT 02_CINE_05_objects.sql ===
-- Ce fichier sql contient la création des tables de la base de données CINE, les contraintes (ALTER TABLE) des tables en question, une séquence
--------------------------------------------------------

--------------------------------------------------------
--  CRÉATION DE LA TABLE "cinemas"
--------------------------------------------------------
create table cine.cinemas (
   id        number generated by default as identity not null,
   nom       varchar2(255) not null,
   adresse   varchar2(255) not null,
   ville     varchar2(255) not null,
   telephone varchar2(20) not null,
   nb_salles number not null
); comment on table cine.cinemas is 'Table des cinémas avec leurs informations principales';


--PRIMARY KEY
alter table cine.cinemas add constraint cinemas_pk primary key ( id );

commit;


--------------------------------------------------------
--  CRÉATION DE LA TABLE "genres"
--------------------------------------------------------
create table cine.genres (
   id          number generated by default as identity not null,
   nom         varchar2(255) not null,
   description clob
); comment on table cine.genres is'Table des genres de films avec leurs descriptions.';


--PRIMARY KEY
alter table cine.genres add constraint genres_pk primary key ( id );

commit;


--------------------------------------------------------
--  CRÉATION DE LA TABLE "films"
--------------------------------------------------------
create table cine.films (
   id             number generated by default as identity not null,
   titre          varchar2(255) not null,
   genre_id       number not null,
   realisateur    varchar2(255) not null,
   annee          number(4,0) not null,
   duree_min      number not null,
   classification varchar2(10) not null,
   budget         number(15,2) not null
); comment on table cine.films is 'Table des films avec leurs informations détaillées.';


--PRIMARY KEY
alter table cine.films add constraint films_pk primary key ( id );

--FOREIGN KEY
alter table cine.films
   add constraint films_genres_fk
      foreign key ( genre_id )
         references cine.genres ( id );

-- f) La classification doit être un choix parmi: « G », « PG », « 13+ », « 16+ » et « 18+ »
alter table cine.films
add constraint ck_films_classification
check (classification in ('G', 'PG', '13+', '16+', '18+'));

commit;


--------------------------------------------------------
--  CRÉATION DE LA TABLE "salles"
--------------------------------------------------------
create table cine.salles (
   id           number generated by default as identity not null,
   cinema_id    number not null,
   numero_salle number not null,
   nb_sieges    number not null,
   type_ecran   varchar2(50) not null
); comment on table cine.salles is 'Table des salles de cinéma avec leurs caractéristiques.';

--PRIMARY KEY
alter table cine.salles add constraint salles_pk primary key ( id );

--FOREIGN KEY
alter table cine.salles
   add constraint salles_cinemas_fk
      foreign key ( cinema_id )
         references cine.cinemas ( id );

commit;


--------------------------------------------------------
--  CRÉATION DE LA TABLE "seances"
--------------------------------------------------------
create table cine.seances (
   id          number generated by default as identity not null,
   salle_id    number not null,
   film_id     number not null,
   date_heure  timestamp not null,
   prix_ticket number(10,2) not null --4) d
); comment on table cine.seances is 'Table des séances de cinéma avec leurs horaires et prix.';

--PRIMARY KEY
alter table cine.seances add constraint seances_pk primary key ( id );

--FOREIGN KEY
alter table cine.seances
   add constraint seances_salles_fk
      foreign key ( salle_id )
         references cine.salles ( id );

alter table cine.seances
   add constraint seances_films_fk
      foreign key ( film_id )
         references cine.films ( id );

--4) d
ALTER TABLE cine.seances
MODIFY prix_ticket DEFAULT 12.99;

commit;


--------------------------------------------------------
--  CRÉATION DE LA TABLE "clients"
--------------------------------------------------------
create table cine.clients (
   id                 number generated by default as identity not null,
   code               varchar2(12),
   prenom             varchar2(255) not null,
   nom                varchar2(255) not null,
   genre              char(1) not null,
   adresse            varchar2(255) not null,
   ville              varchar2(255) not null,
   province           varchar2(255) not null, -- 4) a
   pays               varchar2(255) not null, -- 4) b
   code_postal        varchar2(8) not null,
   telephone          varchar2(14) not null,
   courriel           varchar2(255) not null,
   date_inscription   date not null,
   programme_fidelite varchar2(20) not null -- 4) c
); comment on table cine.clients is 'Table des clients avec leurs informations personnelles et de fidélité.';

-- contraintes PRIMARY KEY
alter table cine.clients
add constraint clients_pk
primary key ( id );

-- 3) d) i : Le genre doit être M ou F ou X
alter table cine.clients
add constraint ck_clients_genre
check (genre in ('M','F','X'));

-- 3) d) ii : Les numéros de téléphone doivent avoir le format suivant : (000)-000-0000
alter table cine.clients
add constraint ck_clients_telephone
check (regexp_like(telephone, '^\([0-9]{3}\)-[0-9]{3}-[0-9]{4}$'));

-- 3) d) iii : Le code de membre doit être 4 lettres suivies de 8 chiffres (ex. : CINE12345678)
alter table cine.clients
add constraint ck_clients_code
check (regexp_like(code, '^[A-Z]{4}[0-9]{8}$'));

-- 3) d) iv : Le pays doit être un choix parmi : « Canada », « États-Unis » et « Mexique ».
alter table cine.clients
add constraint ck_clients_pays
check (pays in ('Canada', 'États-Unis', 'Mexique'));

-- 3) e) Le programme de fidélité doit être un choix parmi: « BRONZE », « SILVER » et « GOLD »
alter table cine.clients
add constraint ck_clients_programme_fidelite
check (programme_fidelite in ('BRONZE', 'SILVER', 'GOLD'));

-- 4) a
alter table cine.clients
modify province default 'Québec';

-- 4) b
alter table cine.clients
modify pays default 'Canada';

-- 4) c
alter table cine.clients
modify programme_fidelite default 'BRONZE';


-- 2) a et b : Séquence pour la table des clients
create sequence cine.seq_clients
start with 77
increment by 3
maxvalue 10000
nocycle;

update cine.clients
   set
    code = 'CINE'
           || lpad(
       cine.seq_clients.nextval,
       8,
       '0'
    )
 where code is null;

commit;

--------------------------------------------------------
--  CRÉATION DE LA TABLE "reservations"
--------------------------------------------------------
create table cine.reservations (
   id               number generated by default as identity not null,
   seance_id        number not null,
   client_id        number not null,
   date_reservation timestamp not null,
   nb_sieges        number not null,
   statut           varchar2(20)  not null, --4) e
   sieges_occupes   varchar2(255) not null,
   prix_ticket      number(10,2) not null
);comment on table cine.reservations is
   'Table des réservations de cinéma avec les détails de la réservation.';
comment on column cine.reservations.sieges_occupes is
   'Liste des sièges occupés pour la réservation qui est formatée comme une chaîne de caractères.';
comment on column cine.reservations.statut is
   'Statut de la réservation.';
comment on column cine.reservations.prix_ticket is
   'Prix du ticket pour la réservation.';
comment on column cine.reservations.nb_sieges is
   'Nombre de sièges réservés.';
comment on column cine.reservations.date_reservation is
   'Date et heure de la réservation.';
comment on column cine.reservations.client_id is
   'Identifiant du client qui a effectué la réservation.';
comment on column cine.reservations.seance_id is
   'Identifiant de la séance pour laquelle la réservation a été faite.';
comment on column cine.reservations.id is
   'Identifiant unique de la réservation.';

--PRIMARY KEY
alter table cine.reservations add constraint reservations_pk primary key ( id );

--FOREIGN KEY
alter table cine.reservations
   add constraint reservations_seances_fk
      foreign key ( seance_id )
         references cine.seances ( id );

alter table cine.reservations
   add constraint reservations_clients_fk
      foreign key ( client_id )
         references cine.clients ( id );

--3) g : La colonne MONTANT_CALCULE doit être calculée automatiquement de la façon suivante: NB_SIEGES × PRIX_TICKET (colonne virtuelle calculée).
alter table cine.reservations
add montant_calcule number(12,2)
generated always as (nb_sieges * prix_ticket) virtual;

--4) e
alter table cine.reservations
modify statut default 'CONFIRMÉE';

commit;

--------------------------------------------------------
-- 6)  INDEX (pour la recherche/tri + les jointures)
--------------------------------------------------------

-- Index sur les clés étrangères (FK)
create index cine.films_genre_id_i on cine.films(genre_id);
create index cine.salles_cinema_id_i on cine.salles(cinema_id);
create index cine.seances_salle_id_i on cine.seances(salle_id);
create index cine.reservations_seance_id_i on cine.reservations(seance_id);
create index cine.reservations_client_id_i on cine.reservations(client_id);

-- Index qui sont utiles pour tri/recherche par date
create index cine.seances_date_heure_i on cine.seances(date_heure);
create index cine.reservations_date_reservation_i on cine.reservations(date_reservation);

-- Contraintes UK
alter table cine.clients add constraint clients_code_uk unique (code);
alter table cine.clients add constraint clients_courriel_uk unique (courriel);

commit;

---------------------------------------------------------
-- 8)  VUE dictionnare_V
---------------------------------------------------------
CREATE OR REPLACE VIEW cine.dictionnaire_v AS
SELECT
    atc.table_name,atc.column_name, atc.data_type, atc.data_length, atc.data_precision,atc.data_scale,atc.nullable, atc.data_default,acc.comments AS commentaires_colonne,
    ac.constraint_type, ac.constraint_name
FROM all_tab_columns atc
LEFT JOIN all_col_comments acc
       ON atc.owner = acc.owner
      AND atc.table_name = acc.table_name
      AND atc.column_name = acc.column_name
LEFT JOIN all_cons_columns acon
       ON atc.owner = acon.owner
      AND atc.table_name = acon.table_name
      AND atc.column_name = acon.column_name
LEFT JOIN all_constraints ac
       ON acon.owner = ac.owner
      AND acon.constraint_name = ac.constraint_name
WHERE atc.owner = 'CINE'
  AND atc.table_name IN ('CINEMAS', 'GENRES', 'FILMS', 'SALLES', 'SEANCES', 'CLIENTS', 'RESERVATIONS')
ORDER BY atc.table_name, atc.column_id;